name: COBS builds

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux_build:
    name: Build and test linux
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.13

    - name: Check out code for the build
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        make test

  mac_build:
    name: Build and test Mac OS 13 with clang
    runs-on: macos-13
    steps:
      - name: Install dependencies
        run: |
          brew install cmake libomp

      - name: Check out code for the build
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build and test
        run: |         
          # set up env variables
          export OpenMP_ROOT=$(brew --prefix libomp)       
          mkdir build
          cd build
          cmake -DSKIP_PYTHON=1 ..
          make
          make test

  mac_arm64_build:
    name: Build and test Mac OS 14 (ARM64) with clang
    runs-on: macos-14
    steps:
      - name: Install dependencies
        run: |
          brew install cmake libomp

      - name: Check out code for the build
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build and test
        run: |         
          # set up env variables
          export OpenMP_ROOT=$(brew --prefix libomp)       
          mkdir build
          cd build
          cmake -DSKIP_PYTHON=1 ..
          make
          make test