name: COBS builds

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  linux_build:
    name: Build and test linux
    runs-on: ubuntu-20.04
    steps:
    - name: Install dependencies
      run: |
        sudo apt-get install cmake
        cmake --version
        gcc --version
        g++ --version

    - name: Check out code for the build
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Build and test
      run: |
        mkdir build
        cd build
        cmake ..
        make
        make test

  mac_build:
    name: Build and test Mac OS X
    runs-on: macos-11
    steps:
      - name: Install dependencies
        run: |
          brew install cmake gcc g++
          which gcc
          which g++
          cmake --version
          gcc --version
          g++ --version

      - name: Check out code for the build
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Build and test
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ ..
          make
          make test